/**
 * Question bank loader.
 *
 * The per-category JSON files in this directory are generated by
 * `npm run gen:questions` from the Highway Code rules, annexes and traffic
 * sign data under `src/content/`. Do not edit them by hand – edit the source
 * material or `scripts/generate-questions.ts` and regenerate.
 *
 * All content is derived from Crown copyright material licensed under the
 * Open Government Licence v3.0 (see `src/content/licence/`).
 */
import type { Category, Question } from '../../types';

import alertness from './alertness.json';
import attitude from './attitude.json';
import safetyMargins from './safety-margins.json';
import hazardAwareness from './hazard-awareness.json';
import vulnerableRoadUsers from './vulnerable-road-users.json';
import vehicleSafety from './vehicle-safety.json';
import motorwayRules from './motorway-rules.json';
import rulesOfTheRoad from './rules-of-the-road.json';
import roadTrafficSigns from './road-traffic-signs.json';
import documents from './documents.json';
import accidents from './accidents.json';
import vehicleLoading from './vehicle-loading.json';
import manifest from './manifest.json';

const BANK: Record<Category, Question[]> = {
  alertness: alertness as Question[],
  attitude: attitude as Question[],
  'safety-margins': safetyMargins as Question[],
  'hazard-awareness': hazardAwareness as Question[],
  'vulnerable-road-users': vulnerableRoadUsers as Question[],
  'vehicle-safety': vehicleSafety as Question[],
  'motorway-rules': motorwayRules as Question[],
  'rules-of-the-road': rulesOfTheRoad as Question[],
  'road-traffic-signs': roadTrafficSigns as Question[],
  documents: documents as Question[],
  accidents: accidents as Question[],
  'vehicle-loading': vehicleLoading as Question[],
};

/** Flat list of every question in the bank. */
export const questions: readonly Question[] = Object.values(BANK).flat();

/** Total question count (matches `manifest.json`). */
export const QUESTION_COUNT = manifest.total;

/** Questions for a single DVSA category, or the full bank for `'mixed'`. */
export function questionsForCategory(category: Category | 'mixed'): readonly Question[] {
  return category === 'mixed' ? questions : BANK[category];
}
